baseurl = "https://tomoseweblog.netlify.com/"
languageCode = "en-us"
title = "blog"
theme = "hyde"
disqusShortname = "tomoseweblog"
[params]
  themeColor = "theme-base-0d"
  layoutReverse = true
  description = "Hi, I'm Tomos Ewe, a web developer from Auckland, New Zealand. This is my blog."