baseurl = "https://blog.tomosewe.com/"
languageCode = "en-us"
title = "Tomos Ewe | blog"
theme = "hyde"
googleAnalytics = "UA-80655492-4"
enableRobotsTXT = true
canonifyURLs = true
[params]
  themeColor = "theme-base-0d"
  layoutReverse = false
  description = "Hi, I'm Tomos Ewe, a web developer from Auckland, New Zealand. This is my blog."
