baseurl = "https://blog.tomosewe.com/"
languageCode = "en-us"
title = "blog"
theme = "hyde"
disqusShortname = "tomoseweblog"
googleAnalytics = "UA-80655492-4"
[params]
  themeColor = "theme-base-0d"
  layoutReverse = false
  description = "Hi, I'm Tomos Ewe, a web developer from Auckland, New Zealand. This is my blog."